# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='duration',
            field=models.DurationField(),
        ),
    ]
