# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questions_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='negative',
            field=models.IntegerField(null=True),
        ),
    ]
