# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20171213_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='negative',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
