# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_contests_contest_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='duration',
        ),
        migrations.AddField(
            model_name='contests',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
