# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_attempts_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempts',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='u_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='contest_id',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='u_id',
        ),
        migrations.DeleteModel(
            name='Attempts',
        ),
        migrations.DeleteModel(
            name='Contests',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
