# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170929_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='problem_id',
        ),
    ]
