# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_remove_questions_problem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('C', 'Correct'), ('W', 'Wrong')], max_length=10)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Contests')),
            ],
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='u_id',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='wrong',
        ),
        migrations.AddField(
            model_name='solution',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Questions'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Questions'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
