# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170929_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='contestants',
            field=models.IntegerField(null=True),
        ),
    ]
