# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_contests_contestants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='end_time',
        ),
        migrations.AddField(
            model_name='contests',
            name='duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
