# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_auto_20170909_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempts',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='attempts',
            name='u_id',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='max_score',
            new_name='attempts',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='image',
        ),
        migrations.AddField(
            model_name='questions',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='u_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Attempts',
        ),
    ]
