# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20170929_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='contests',
            name='rules',
            field=models.CharField(default='Some rules', max_length=200),
        ),
    ]
