# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20171001_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='duration',
        ),
        migrations.AddField(
            model_name='contests',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
