# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20171004_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='image_url',
        ),
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
