# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20171004_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
