# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20171005_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
