# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20171006_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
    ]
