# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_auto_20171006_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
