# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20171006_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='q_id',
        ),
        migrations.AddField(
            model_name='questions',
            name='option',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='solution',
        ),
    ]
