# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20170927_2112'),
        ('quiz', '0024_auto_20171012_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Contests')),
                ('members', models.ManyToManyField(to='crypto.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='registrations',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.team'),
        ),
    ]
