# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20171014_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Team'),
        ),
    ]
