# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20171015_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Team'),
        ),
    ]
