# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_auto_20171015_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Team'),
        ),
    ]
