# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20170909_2013'),
        ('crypto', '0005_remove_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Contests'),
        ),
    ]
