# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_profile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roll_2',
        ),
    ]
