# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_remove_profile_roll_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='roll_1',
            new_name='roll',
        ),
    ]
